### ISSUE TITLE
questions/suggestions

### ISSUE THREAD

**Issue by m-hugo** [oasislinux/oasis#12]
use s6 instead of perp/sinit
https://skarnet.org/software/s6

why do you use sbase/ubase instead of coreutils, busybox or toybox,
the old ld instead of gold or lld,
libressl instead of openssl,
rc instead of a true shell ?

**Comment by michaelforney** [comment]
You haven't given me any reasons why you think those alternatives are better. I'm also getting a little tired of these "why not X instead of Y?" discussions. If you really think there is some software that would be a better choice for oasis, you'll have to back it up with some compelling evidence.

> use s6 instead of perp/sinit
> https://skarnet.org/software/s6

Both are good service supervisors. I prefer the command-line interface of perp to s6, and don't need all of the extra features of s6.

Though, I may consider switching at some point.

> why do you use sbase/ubase instead of coreutils, busybox or toybox,

Look at the code of coreutils and busybox and you'll see why.

toybox aims to be compatible with GNU tools, while sbase aims to be closer to plain POSIX.

> the old ld instead of gold or lld,

gold and lld are both written in C++.

> libressl instead of openssl,

Actually, bearssl is used when possible, and I aim to switch to it completely.

> rc instead of a true shell ?

Both rc and POSIX sh are provided. rc has a smaller and more consistent language than sh, so I like to use it when possible.

**Comment by m-hugo** [comment]
> You haven't given me any reasons why you think those alternatives are better. I'm also getting a little tired of these "why not X instead of Y?" discussions. If you really think there is some software that would be a better choice for oasis, you'll have to back it up with some compelling evidence.
> 
i'm glad you like them, here's another one,
why not su/sudo/sudoku instead of doas?

> > why do you use sbase/ubase instead of coreutils, busybox or toybox,
> 
> Look at the code of coreutils and busybox and you'll see why.
> 
i think a code hard to understand but easy to use is better than the opposite,
too much bloat is also bad but i think busybox is the best compromise

> > the old ld instead of gold or lld,
> 
> gold and lld are both written in C++.
> 
ld is 2 to 30x slower than lld and not very good with lto, why do you hate c++ ?
> > libressl instead of openssl,
> 
it sucks so much alpine switched back to openssl
"We are volunteers so it will be finished when it is finished" is not a great motto for a critical library 

> Actually, bearssl is used when possible, and I aim to switch to it completely.
> 
it doesn't change the tls 1.3 problem,
open, boring and wolf are now the most proactive tls libraries.

> > rc instead of a true shell ?
> 
> Both rc and POSIX sh are provided. rc has a smaller and more consistent language than sh, so I like to use it when possible.
>
like sbase and perp i think it's too limited to be usable, but if it works for you 🤷
