### ISSUE TITLE
Xorg?

### ISSUE THREAD

**Issue by luizbra** [oasislinux/oasis#27]
Hi! I would like to know if it is possible to run Xorg on oasis.

**Comment by harrisonrobin** [comment]
On the base configuration it is not supported however it is possible. By design, oasis targets the wayland protocol exclusively. The included display server velox has some xwayland support code in the underlying swc library which could require the relevant X libraries to available at build time. Since oasis is package manager agnostic, for xorg support you can use nix packages to install an xorg server.  Personally, i could use a statically linked tinyx binary with a framebuffer or vesa backend. Last I remember morpheous linux had a repository with compiled static binaries, which i think aligns better which the overall oasis way of doing things, getting 80% of the functionality in 20% of code. Good luck!
________________________________
From: luizbra ***@***.***>
Sent: Wednesday, September 1, 2021 8:54 AM
To: oasislinux/oasis ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [oasislinux/oasis] Xorg? (#27)


Hi! I would like to know if it is possible to run Xorg on oasis.

**Comment by michaelforney** [comment]
What @harrisonrobin said is correct.

Personally, I have Xorg and Xwayland installed through pkgsrc so I can run X11-specific applications from time to time. If you wanted, you could just skip the GUI packages from oasis, and grab X11 packages from pkgsrc/nix
